data = {
  result: "OK",
  TransferSearchMode: "SEMI_AUTO",
  timestamp: "20.10.2018 16:00:37.856",
  flFPKRoundBonus: false,
  tp: [
    {
      state: "Trains",
      expressErr: false,
      msgList: [],
      from: "МОСКВА",
      where: "САНКТ-ПЕТЕРБУРГ",
      date: "20.10.2018",
      fromCode: 2000000,
      whereCode: 2004000,
      defShowTime: "local",
      test_language: "ru",
      list: [
        {
          brandId: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "17:30",
          date1: "20.10.2018",
          time1: "21:16",
          brand: "САПСАН",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "772А",
          number: "772А",
          typeEx: "0",
          uid: "772AJ_1540045800000_1540059360000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "17:30",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ДОСС",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "03:46",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "92",
              itype: "3",
              servCls: "1Р",
              tariff: "3598",
              pt: "1077",
              typeLoc: "Сидячий",
              type: "Сид"
            }
          ],
          hints: []
        },
        {
          brandId: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "17:40",
          date1: "20.10.2018",
          time1: "21:35",
          brand: "САПСАН",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "774А",
          number: "774А",
          typeEx: "0",
          uid: "774AJ_1540046400000_1540060500000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "17:40",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ДОСС",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "03:55",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "117",
              itype: "3",
              servCls: "1Р",
              tariff: "3098",
              pt: "927",
              typeLoc: "Сидячий",
              type: "Сид"
            }
          ],
          hints: []
        },
        {
          brandId: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "19:30",
          date1: "20.10.2018",
          time1: "23:25",
          brand: "САПСАН",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "776А",
          number: "776А",
          typeEx: "0",
          uid: "776AJ_1540053000000_1540067100000",
          bEntire: false,
          disabledType: true,
          flMsk: "3",
          new: false,
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "19:30",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ДОСС",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "03:55",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "547",
              itype: "3",
              servCls: "1Р",
              tariff: "3098",
              pt: "927",
              typeLoc: "Сидячий",
              type: "Сид"
            }
          ],
          hints: []
        },
        {
          brandId: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "19:40",
          date1: "20.10.2018",
          time1: "23:44",
          brand: "САПСАН",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "778А",
          number: "778А",
          typeEx: "0",
          uid: "778AJ_1540053600000_1540068240000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "19:40",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ДОСС",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "04:04",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "108",
              itype: "3",
              servCls: "1Р",
              tariff: "3186",
              pt: "954",
              typeLoc: "Сидячий",
              type: "Сид"
            }
          ],
          hints: []
        },
        {
          brandId: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "21:00",
          date1: "21.10.2018",
          time1: "00:40",
          brand: "САПСАН",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "780А",
          number: "780А",
          typeEx: "0",
          uid: "780AJ_1540058400000_1540071600000",
          bEntire: false,
          disabledType: true,
          flMsk: "3",
          new: false,
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "21:00",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ДОСС",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "03:40",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "90",
              itype: "3",
              servCls: "1Р",
              tariff: "3598",
              pt: "1077",
              typeLoc: "Сидячий",
              type: "Сид"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "89",
          time0: "21:20",
          date1: "21.10.2018",
          time1: "05:01",
          route0: "МАХАЧКАЛА",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "136*С",
          number: "135С",
          typeEx: "0",
          uid: "135SJ_1540059600000_1540087260000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "18.10.2018",
          trTime0: "19:37",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА КУРСКАЯ (КУРСКИЙ ВОКЗАЛ)",
          timeInWay: "07:41",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "7",
              itype: "6",
              servCls: "1У",
              tariff: "4755",
              pt: "1423",
              typeLoc: "СВ",
              type: "Люкс"
            },
            {
              freeSeats: "1",
              itype: "4",
              servCls: "2К",
              tariff: "3537",
              pt: "1058",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "89",
          time0: "21:41",
          date1: "21.10.2018",
          time1: "07:30",
          route0: "БЕЛГОРОД",
          route1: "С-ПЕТ-ЛАД",
          number2: "120В",
          number: "120В",
          typeEx: "0",
          uid: "120VJ_1540060860000_1540096200000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "09:40",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА КУРСКАЯ (КУРСКИЙ ВОКЗАЛ)",
          timeInWay: "09:49",
          station1: "САНКТ-ПЕТЕРБУРГ ЛАДОЖ.",
          cars: [
            {
              freeSeats: "16",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "86",
              itype: "4",
              servCls: "2К",
              tariff: "2698",
              pt: "808",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          bFirm: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "21:49",
          date1: "21.10.2018",
          time1: "05:32",
          brand: "Самара",
          route0: "САМАРА",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "108*Й",
          number: "107Й",
          typeEx: "0",
          uid: "107JI_1540061340000_1540089120000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "19.10.2018",
          trTime0: "22:15",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА КУРСКАЯ (КУРСКИЙ ВОКЗАЛ)",
          timeInWay: "07:43",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "66",
              itype: "4",
              servCls: "2Э",
              tariff: "3372",
              pt: "1009",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          bFirm: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "21:50",
          date1: "21.10.2018",
          time1: "06:06",
          brand: "Смена-А. Бетанкур (двухэтажный)",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "026А",
          number: "026А",
          typeEx: "0",
          uid: "026AJ_1540061400000_1540091160000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "21:50",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "08:16",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "177",
              itype: "4",
              servCls: "2Э",
              tariff: "2259",
              pt: "676",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "59",
          time0: "22:15",
          date1: "21.10.2018",
          time1: "05:39",
          route0: "МОСКВА ОКТ",
          route1: "ТАЛЛИНН П",
          number2: "034А",
          number: "034А",
          typeEx: "0",
          uid: "034AJ_1540062900000_1540089540000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "22:15",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "07:24",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "17",
              itype: "6",
              servCls: "1У",
              tariff: "6198",
              pt: "1855",
              typeLoc: "СВ",
              type: "Люкс"
            },
            {
              freeSeats: "82",
              itype: "4",
              servCls: "2К",
              tariff: "2429",
              pt: "727",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "89",
          time0: "22:16",
          date1: "21.10.2018",
          time1: "06:16",
          route0: "ЧЕЛЯБИНСК",
          route1: "С-ПЕТ-ЛАД",
          number2: "146У",
          number: "146У",
          typeEx: "0",
          uid: "146UJ_1540062960000_1540091760000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "19.10.2018",
          trTime0: "10:30",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА КУРСКАЯ (КУРСКИЙ ВОКЗАЛ)",
          timeInWay: "08:00",
          station1: "САНКТ-ПЕТЕРБУРГ ЛАДОЖ.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "12",
              itype: "6",
              servCls: "1У",
              tariff: "4365",
              pt: "1306",
              typeLoc: "СВ",
              type: "Люкс"
            },
            {
              freeSeats: "25",
              itype: "4",
              servCls: "2Л",
              tariff: "2226",
              pt: "666",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "89",
          time0: "22:28",
          date1: "21.10.2018",
          time1: "06:40",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "028А",
          number: "028А",
          typeEx: "0",
          uid: "028AJ_1540063680000_1540093200000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "22:28",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "08:12",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "6",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "19",
              itype: "4",
              servCls: "2К",
              tariff: "2566",
              pt: "768",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          bFirm: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "22:50",
          date1: "21.10.2018",
          time1: "06:47",
          brand: "Санкт-Петербург – Москва (двухэтажный)",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "006А",
          number: "006А",
          typeEx: "0",
          uid: "006AJ_1540065000000_1540093620000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "22:50",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "07:57",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "35",
              itype: "4",
              servCls: "2Э",
              tariff: "2659",
              pt: "796",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          date0: "20.10.2018",
          depth: "89",
          time0: "23:40",
          date1: "21.10.2018",
          time1: "08:36",
          brand: "ГРАНД ЭКСПРЕСС",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "054Ч",
          number: "054Ч",
          typeEx: "0",
          uid: "054CH_1540068000000_1540100160000",
          bEntire: false,
          bWifi: "1",
          flMsk: "3",
          new: false,
          inetInfo: "Во всех вагонах поезда имеется WiFi-доступ в интернет.",
          varPrice: false,
          trDate0: "20.10.2018",
          trTime0: "23:40",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ГРАНД",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "08:56",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "51",
              itype: "6",
              servCls: "1Б",
              tariff: "5863",
              typeLoc: "СВ",
              type: "Люкс"
            },
            {
              freeSeats: "24",
              itype: "5",
              servCls: "1А",
              tariff: "18355",
              typeLoc: "Люкс",
              type: "Мягкий"
            },
            {
              freeSeats: "34",
              itype: "4",
              servCls: "2Э",
              tariff: "3694",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        },
        {
          bFirm: "1",
          date0: "20.10.2018",
          depth: "89",
          time0: "23:55",
          date1: "21.10.2018",
          time1: "07:55",
          brand: "Красная стрела",
          route0: "МОСКВА ОКТ",
          route1: "С-ПЕТЕР-ГЛ",
          number2: "002А",
          number: "002А",
          typeEx: "0",
          uid: "002AJ_1540068900000_1540097700000",
          bEntire: false,
          flMsk: "3",
          new: false,
          varPrice: true,
          trDate0: "20.10.2018",
          trTime0: "23:55",
          deferredPayment: false,
          elReg: true,
          train_id: "0",
          carrier: "ФПК",
          type: "0",
          station0: "МОСКВА ОКТЯБРЬСКАЯ (ЛЕНИНГРАДСКИЙ ВОКЗАЛ)",
          timeInWay: "08:00",
          station1: "САНКТ-ПЕТЕРБУРГ-ГЛАВН.",
          cars: [
            {
              freeSeats: "8",
              itype: "7",
              servCls: "null",
              tariff: "0",
              typeLoc: "Багажное купе",
              type: "Багаж"
            },
            {
              freeSeats: "99",
              itype: "6",
              servCls: "1Э",
              tariff: "5767",
              pt: "1726",
              typeLoc: "СВ",
              type: "Люкс"
            },
            {
              freeSeats: "52",
              itype: "4",
              servCls: "2Э",
              tariff: "3411",
              pt: "1021",
              typeLoc: "Купе",
              type: "Купе"
            }
          ],
          hints: []
        }
      ]
    }
  ],
  discounts: {},
  tipFlags: { Ukr: 0 }
};

module.exports = { data };
